
.PHONY: plan
plan: ## Runs a terraform plan w/ variables.tfvars as input
	terraform plan -var-file=terraform.tfvars

.PHONY: apply
apply: ## Runs a terraform apply w/ variables.tfvars as input
	terraform apply -var-file=terraform.tfvars
